name: native_sqlite_inspector
description: DevTools Inspector for Native SQLite - Inspect SQLite databases in real-time during development
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  devtools_extensions: ^0.5.1
  native_sqlite: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
