import 'package:analyzer/dart/element/element.dart';
import 'package:build/build.dart';
import 'package:glob/glob.dart';
import 'package:source_gen/source_gen.dart';

import '../analyzer/table_analyzer.dart';
import '../config/generator_options.dart';
import '../models/table_info.dart';

/// Generator that creates a centralized schema registry for all auto-managed tables.
///
/// This generator scans all Dart files for @DbTable annotations with auto=true,
/// analyzes their schemas, and generates a DatabaseSchemaRegistry class that
/// contains all table creation SQL and dependency ordering.
class SchemaRegistryGenerator extends Generator {
  final GeneratorOptions options;

  SchemaRegistryGenerator(this.options);

  @override
  Future<String> generate(LibraryReader library, BuildStep buildStep) async {
    // Only generate for a specific trigger file
    if (!buildStep.inputId.path.endsWith('lib/database_schema.dart')) {
      return '';
    }

    final resolver = buildStep.resolver;
    final tables = <TableInfo>[];
    final tableFiles = <String, String>{}; // dartName -> filename

    // Scan all Dart files in lib/ for @DbTable annotations
    final dartFiles = Glob('lib/**.dart');

    await for (final assetId in buildStep.findAssets(dartFiles)) {
      try {
        if (await resolver.isLibrary(assetId)) {
          final lib = await resolver.libraryFor(assetId);
          final reader = LibraryReader(lib);
          final tableChecker = TypeChecker.fromUrl(
            'package:native_sqlite_annotations/src/table.dart#DbTable',
          );

          for (final annotatedElement in reader.annotatedWith(tableChecker)) {
            final element = annotatedElement.element;
            if (element is! ClassElement) continue;

            // Get the annotation
            final annotation = annotatedElement.annotation;
            final autoValue = annotation.read('auto').literalValue as bool?;

            // Skip if auto is explicitly set to false
            if (autoValue == false) {
              print('Skipping table ${element.name} (auto=false)');
              continue;
            }

            try {
              final analyzer = TableAnalyzer(options);
              final tableInfo = analyzer.analyze(element, annotation);
              tables.add(tableInfo);

              // Extract filename from assetId path
              final pathParts = assetId.path.split('/');
              final fileName = pathParts.last.replaceAll('.dart', '');
              tableFiles[tableInfo.dartName] = fileName;

              print(
                'Found auto-managed table: ${tableInfo.sqlName} in $fileName.dart',
              );
            } catch (e) {
              print('Failed to analyze table ${element.name}: $e');
            }
          }
        }
      } catch (e) {
        print('Error processing ${assetId.path}: $e');
      }
    }

    if (tables.isEmpty) {
      print('No auto-managed tables found');
      return '';
    }

    // Sort tables by dependencies (foreign keys)
    final sortedTables = _topologicalSort(tables);

    return _generateRegistry(sortedTables, tableFiles);
  }

  /// Performs topological sort on tables based on foreign key dependencies.
  /// Returns tables in the order they should be created.
  List<TableInfo> _topologicalSort(List<TableInfo> tables) {
    final sorted = <TableInfo>[];
    final visited = <String>{};
    final visiting = <String>{};

    void visit(TableInfo table) {
      if (visited.contains(table.sqlName)) return;

      if (visiting.contains(table.sqlName)) {
        throw Exception(
          'Circular dependency detected involving table: ${table.sqlName}',
        );
      }

      visiting.add(table.sqlName);

      // Visit dependencies first (tables referenced by foreign keys)
      for (final column in table.columns) {
        if (column.hasForeignKey) {
          final referencedTable = column.foreignKeyTable!;
          final dependency = tables.firstWhere(
            (t) => t.sqlName == referencedTable,
            orElse: () => throw Exception(
              'Foreign key references unknown table: $referencedTable',
            ),
          );
          visit(dependency);
        }
      }

      visiting.remove(table.sqlName);
      visited.add(table.sqlName);
      sorted.add(table);
    }

    for (final table in tables) {
      visit(table);
    }

    return sorted;
  }

  /// Generates the DatabaseManager class code.
  String _generateRegistry(
    List<TableInfo> tables,
    Map<String, String> tableFiles,
  ) {
    final buffer = StringBuffer();

    // File header
    buffer.writeln('// coverage:ignore-file');
    buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
    buffer.writeln('// Generated by native_sqlite_generator');
    buffer.writeln(
      '// This file is automatically generated and should not be manually edited.',
    );
    buffer.writeln();
    buffer.writeln("import 'package:flutter/foundation.dart';");
    buffer.writeln("import 'package:native_sqlite/native_sqlite.dart';");
    buffer.writeln();

    // Import all schema classes using absolute paths from lib/
    for (final table in tables) {
      final fileName =
          tableFiles[table.dartName] ?? _toSnakeCase(table.dartName);
      buffer.writeln(
        "import 'package:native_sqlite_example/models/$fileName.dart';",
      );
    }
    buffer.writeln();

    // Class definition
    buffer.writeln('/// Auto-generated database manager.');
    buffer.writeln('///');
    buffer.writeln(
      '/// This class handles all database lifecycle operations including:',
    );
    buffer.writeln('/// - Initialization and opening');
    buffer.writeln('/// - Table creation and migration');
    buffer.writeln('/// - Schema versioning');
    buffer.writeln('/// - Cleanup and closing');
    buffer.writeln('///');
    buffer.writeln('/// Simply call `DatabaseManager.init()` at app startup,');
    buffer.writeln('/// and everything else is handled automatically.');
    buffer.writeln('class DatabaseManager {');
    buffer.writeln('  DatabaseManager._();');
    buffer.writeln();
    buffer.writeln('  static bool _initialized = false;');
    buffer.writeln('  static String? _currentDatabaseName;');
    buffer.writeln();

    // Schema version (based on content hash)
    final schemaHash = _calculateSchemaHash(tables);
    buffer.writeln('  /// Current schema version (based on content hash).');
    buffer.writeln('  static const schemaVersion = $schemaHash;');
    buffer.writeln();

    // Table map
    buffer.writeln(
      '  /// Map of table names to their CREATE TABLE SQL statements.',
    );
    buffer.writeln('  static const tables = <String, String>{');
    for (final table in tables) {
      buffer.writeln(
        "    '${table.sqlName}': ${table.dartName}Schema.createTableSql,",
      );
    }
    buffer.writeln('  };');
    buffer.writeln();

    // onCreate statements (ordered)
    buffer.writeln(
      '  /// Ordered list of SQL statements for database creation.',
    );
    buffer.writeln('  ///');
    buffer.writeln(
      '/// Tables are ordered to respect foreign key dependencies.',
    );
    buffer.writeln('  static List<String> get onCreateStatements => [');

    // Add CREATE TABLE statements
    for (final table in tables) {
      buffer.writeln('    ${table.dartName}Schema.createTableSql,');
    }

    // Add indexes
    for (final table in tables) {
      if (table.hasIndexes) {
        buffer.writeln('    ...${table.dartName}Schema.indexSql,');
      }
    }

    buffer.writeln('  ];');
    buffer.writeln();

    // Table names getter
    buffer.writeln('  /// List of all auto-managed table names.');
    buffer.writeln('  static List<String> get tableNames => [');
    for (final table in tables) {
      buffer.writeln("    '${table.sqlName}',");
    }
    buffer.writeln('  ];');
    buffer.writeln();

    // Add comprehensive database lifecycle methods
    _generateInitMethod(buffer);
    _generateCloseMethod(buffer);
    _generateCreateTablesMethod(buffer);
    _generateDropTableMethod(buffer);
    _generateGetDatabaseMethod(buffer);
    _generateIsInitializedGetter(buffer);

    buffer.writeln('}');

    return buffer.toString();
  }

  void _generateInitMethod(StringBuffer buffer) {
    buffer.writeln('  /// Initialize the database with automatic setup.');
    buffer.writeln('  ///');
    buffer.writeln('  /// This method handles:');
    buffer.writeln('  /// - Opening/creating the database');
    buffer.writeln('  /// - Creating tables in dependency order');
    buffer.writeln('  /// - Running migrations when schema changes');
    buffer.writeln('  /// - Setting up indexes');
    buffer.writeln('  ///');
    buffer.writeln('  /// Call this once at app startup:');
    buffer.writeln('  /// ```dart');
    buffer.writeln('  /// void main() async {');
    buffer.writeln('  ///   WidgetsFlutterBinding.ensureInitialized();');
    buffer.writeln('  ///   await DatabaseManager.init();');
    buffer.writeln('  ///   runApp(MyApp());');
    buffer.writeln('  /// }');
    buffer.writeln('  /// ```');
    buffer.writeln('  static Future<void> init({');
    buffer.writeln('    String name = \'app_database\',');
    buffer.writeln('    bool enableWAL = true,');
    buffer.writeln('    bool enableForeignKeys = true,');
    buffer.writeln('    bool dropRemovedTables = false,');
    buffer.writeln(
      '    Future<void> Function(String databaseName, int oldVersion, int newVersion)? onCustomMigrate,',
    );
    buffer.writeln('  }) async {');
    buffer.writeln('    if (_initialized) {');
    buffer.writeln(
      '      debugPrint(\'DatabaseManager: Already initialized\');',
    );
    buffer.writeln('      return;');
    buffer.writeln('    }');
    buffer.writeln();
    buffer.writeln(
      '    debugPrint(\'DatabaseManager: Initializing database "\$name"\');',
    );
    buffer.writeln('    debugPrint(\'  Schema version: \$schemaVersion\');');
    buffer.writeln(
      '    debugPrint(\'  Tables: \${tableNames.join(\", \")}\');',
    );
    buffer.writeln();
    buffer.writeln('    _currentDatabaseName = name;');
    buffer.writeln();
    buffer.writeln('    await NativeSqlite.open(');
    buffer.writeln('      config: AutoMigration.createConfig(');
    buffer.writeln('        name: name,');
    buffer.writeln('        schemaVersion: schemaVersion,');
    buffer.writeln('        onCreateStatements: onCreateStatements,');
    buffer.writeln('        tables: tables,');
    buffer.writeln('        tableNames: tableNames,');
    buffer.writeln('        enableWAL: enableWAL,');
    buffer.writeln('        enableForeignKeys: enableForeignKeys,');
    buffer.writeln('        dropRemovedTables: dropRemovedTables,');
    buffer.writeln('        onCustomMigrate: onCustomMigrate,');
    buffer.writeln('      ),');
    buffer.writeln('    );');
    buffer.writeln();
    buffer.writeln('    _initialized = true;');
    buffer.writeln(
      '    debugPrint(\'DatabaseManager: Initialization complete\');',
    );
    buffer.writeln('  }');
    buffer.writeln();
  }

  void _generateCloseMethod(StringBuffer buffer) {
    buffer.writeln('  /// Close the database and release resources.');
    buffer.writeln('  ///');
    buffer.writeln('  /// Call this when shutting down the app or when');
    buffer.writeln('  /// you need to reinitialize with different settings.');
    buffer.writeln('  static Future<void> close() async {');
    buffer.writeln('    if (!_initialized || _currentDatabaseName == null) {');
    buffer.writeln(
      '      debugPrint(\'DatabaseManager: Not initialized, nothing to close\');',
    );
    buffer.writeln('      return;');
    buffer.writeln('    }');
    buffer.writeln();
    buffer.writeln(
      '    debugPrint(\'DatabaseManager: Closing database "\$_currentDatabaseName"\');',
    );
    buffer.writeln('    await NativeSqlite.close(_currentDatabaseName!);');
    buffer.writeln('    _initialized = false;');
    buffer.writeln('    _currentDatabaseName = null;');
    buffer.writeln('    debugPrint(\'DatabaseManager: Database closed\');');
    buffer.writeln('  }');
    buffer.writeln();
  }

  void _generateCreateTablesMethod(StringBuffer buffer) {
    buffer.writeln(
      '  /// Create all tables (useful for testing or manual setup).',
    );
    buffer.writeln('  ///');
    buffer.writeln('  /// This is called automatically by init(), but can be');
    buffer.writeln('  /// used manually if needed.');
    buffer.writeln(
      '  static Future<void> createTables([String? databaseName]) async {',
    );
    buffer.writeln('    final db = databaseName ?? _currentDatabaseName;');
    buffer.writeln('    if (db == null) {');
    buffer.writeln(
      '      throw StateError(\'Database not initialized. Call init() first.\');',
    );
    buffer.writeln('    }');
    buffer.writeln();
    buffer.writeln(
      '    debugPrint(\'DatabaseManager: Creating tables for "\$db"\');',
    );
    buffer.writeln();
    buffer.writeln('    for (final statement in onCreateStatements) {');
    buffer.writeln('      await NativeSqlite.execute(db, statement);');
    buffer.writeln('    }');
    buffer.writeln();
    buffer.writeln('    debugPrint(\'DatabaseManager: All tables created\');');
    buffer.writeln('  }');
    buffer.writeln();
  }

  void _generateDropTableMethod(StringBuffer buffer) {
    buffer.writeln('  /// Drop a specific table from the database.');
    buffer.writeln('  ///');
    buffer.writeln(
      '  /// WARNING: This permanently deletes all data in the table.',
    );
    buffer.writeln(
      '  static Future<void> dropTable(String tableName, {String? databaseName}) async {',
    );
    buffer.writeln('    final db = databaseName ?? _currentDatabaseName;');
    buffer.writeln('    if (db == null) {');
    buffer.writeln(
      '      throw StateError(\'Database not initialized. Call init() first.\');',
    );
    buffer.writeln('    }');
    buffer.writeln();
    buffer.writeln('    if (!tableNames.contains(tableName)) {');
    buffer.writeln(
      '      throw ArgumentError(\'Unknown table: \$tableName. Available tables: \${tableNames.join(\", \")}\');',
    );
    buffer.writeln('    }');
    buffer.writeln();
    buffer.writeln(
      '    debugPrint(\'DatabaseManager: Dropping table "\$tableName"\');',
    );
    buffer.writeln(
      '    await NativeSqlite.execute(db, \'DROP TABLE IF EXISTS \$tableName\');',
    );
    buffer.writeln(
      '    debugPrint(\'DatabaseManager: Table "\$tableName" dropped\');',
    );
    buffer.writeln('  }');
    buffer.writeln();
  }

  void _generateGetDatabaseMethod(StringBuffer buffer) {
    buffer.writeln('  /// Get the current database name.');
    buffer.writeln('  ///');
    buffer.writeln('  /// Throws if database is not initialized.');
    buffer.writeln('  /// Use this with NativeSqlite methods:');
    buffer.writeln('  /// ```dart');
    buffer.writeln('  /// final dbName = DatabaseManager.currentDatabase;');
    buffer.writeln(
      '  /// await NativeSqlite.query(dbName, \'SELECT * FROM users\');',
    );
    buffer.writeln('  /// ```');
    buffer.writeln('  static String get currentDatabase {');
    buffer.writeln('    if (!_initialized || _currentDatabaseName == null) {');
    buffer.writeln(
      '      throw StateError(\'Database not initialized. Call DatabaseManager.init() first.\');',
    );
    buffer.writeln('    }');
    buffer.writeln('    return _currentDatabaseName!;');
    buffer.writeln('  }');
    buffer.writeln();
  }

  void _generateIsInitializedGetter(StringBuffer buffer) {
    buffer.writeln('  /// Check if database is initialized.');
    buffer.writeln('  static bool get isInitialized => _initialized;');
    buffer.writeln();
    buffer.writeln('  /// Get the current database name.');
    buffer.writeln(
      '  static String? get databaseName => _currentDatabaseName;',
    );
    buffer.writeln();
  }

  void _generateDeprecatedMethod(StringBuffer buffer) {
    buffer.writeln('  /// @deprecated Use DatabaseManager.init() instead.');
    buffer.writeln('  ///');
    buffer.writeln(
      '  /// Creates a DatabaseConfig with automatic migration support.',
    );
    buffer.writeln(
      '  @Deprecated(\'Use DatabaseManager.init() instead for simpler setup\')',
    );
    buffer.writeln('  static DatabaseConfig createAutoMigratedConfig({');
    buffer.writeln('    required String name,');
    buffer.writeln('    bool enableWAL = true,');
    buffer.writeln('    bool enableForeignKeys = true,');
    buffer.writeln('    bool dropRemovedTables = false,');
    buffer.writeln(
      '    Future<void> Function(String databaseName, int oldVersion, int newVersion)? onCustomMigrate,',
    );
    buffer.writeln('  }) {');
    buffer.writeln('    return AutoMigration.createConfig(');
    buffer.writeln('      name: name,');
    buffer.writeln('      schemaVersion: schemaVersion,');
    buffer.writeln('      onCreateStatements: onCreateStatements,');
    buffer.writeln('      tables: tables,');
    buffer.writeln('      tableNames: tableNames,');
    buffer.writeln('      enableWAL: enableWAL,');
    buffer.writeln('      enableForeignKeys: enableForeignKeys,');
    buffer.writeln('      dropRemovedTables: dropRemovedTables,');
    buffer.writeln('      onCustomMigrate: onCustomMigrate,');
    buffer.writeln('    );');
    buffer.writeln('  }');
    buffer.writeln();
  }

  /// Calculates a simple hash of all table schemas for versioning.
  int _calculateSchemaHash(List<TableInfo> tables) {
    final content = tables.map((t) => t.sqlName).join(',');
    return content.hashCode.abs() % 1000000; // Keep it reasonable
  }

  /// Converts a string to snake_case.
  String _toSnakeCase(String input) {
    return input
        .replaceAllMapped(
          RegExp(r'([A-Z])'),
          (match) => '_${match.group(1)!.toLowerCase()}',
        )
        .replaceFirst(RegExp(r'^_'), '');
  }
}
