import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:analyzer/dart/element/element.dart';
import 'package:build/build.dart';
import 'package:glob/glob.dart';
import 'package:source_gen/source_gen.dart';

import '../analyzer/table_analyzer.dart';
import '../config/generator_options.dart';
import '../models/table_info.dart';

/// Builder that automatically generates DatabaseManager.
///
/// Works like Flutter's l10n - NO trigger file needed!
/// Just run build_runner and DatabaseManager is ready to use.
class SchemaRegistryBuilder implements Builder {
  final GeneratorOptions options;
  bool _hasRun = false;

  SchemaRegistryBuilder(this.options);

  @override
  Map<String, List<String>> get buildExtensions {
    return const {
      r'$lib$': ['generated/database_manager.dart'],
    };
  }

  @override
  Future<void> build(BuildStep buildStep) async {
    // Only run once per build (like Flutter's l10n)
    if (_hasRun) return;
    _hasRun = true;

    log.info('🔧 Generating DatabaseManager...');

    final packageName = buildStep.inputId.package;
    final resolver = buildStep.resolver;
    final tables = <TableInfo>[];
    final tableFiles = <String, String>{};

    // Read schema via build system to declare dependency on migration builder
    // and avoid dart:io timing issues (file may not be flushed to disk yet).
    final schemaAsset = AssetId(packageName, 'lib/generated/native_sqlite_schema.json');
    String? schemaContent;
    if (await buildStep.canRead(schemaAsset)) {
      schemaContent = await buildStep.readAsString(schemaAsset);
    }

    // Scan all Dart files for @DbTable annotations
    final dartFiles = Glob('lib/**.dart');
    final assets = await buildStep.findAssets(dartFiles).toList();

    for (final assetId in assets) {
      try {
        if (!await resolver.isLibrary(assetId)) continue;

        final lib = await resolver.libraryFor(assetId);
        final reader = LibraryReader(lib);
        final tableChecker = TypeChecker.fromUrl(
          'package:native_sqlite_annotations/src/table.dart#DbTable',
        );

        for (final annotatedElement in reader.annotatedWith(tableChecker)) {
          final element = annotatedElement.element;
          if (element is! ClassElement) continue;

          final annotation = annotatedElement.annotation;
          final autoValue = annotation.read('auto').literalValue as bool?;

          // Skip if auto=false
          if (autoValue == false) continue;

          try {
            final analyzer = TableAnalyzer(options);
            final tableInfo = analyzer.analyze(element, annotation);
            tables.add(tableInfo);

            // Store path relative to lib/ (without extension) so the import
            // is reconstructed as package:<pkg>/<rel_path>.dart
            final relPath = assetId.path
                .replaceFirst('lib/', '')
                .replaceAll('.dart', '');
            tableFiles[tableInfo.dartName] = relPath;
          } catch (e) {
            log.warning('⚠️  Failed to analyze ${element.name}: $e');
          }
        }
      } catch (e) {
        log.fine('Skipping ${assetId.path}: $e');
      }
    }

    if (tables.isEmpty) {
      log.warning(
        '⚠️  No @DbTable models found. DatabaseManager not generated.',
      );
      return;
    }

    log.info('✅ Found ${tables.length} tables');

    final sortedTables = _topologicalSort(tables);
    final code = _generateCode(sortedTables, tableFiles, packageName, schemaContent);

    // Write to fixed location: lib/generated/database_manager.dart
    await buildStep.writeAsString(
      AssetId(packageName, 'lib/generated/database_manager.dart'),
      code,
    );

    log.info('✅ generated/database_manager.dart');
  }

  List<TableInfo> _topologicalSort(List<TableInfo> tables) {
    final sorted = <TableInfo>[];
    final visited = <String>{};
    final visiting = <String>{};

    void visit(TableInfo table) {
      if (visited.contains(table.sqlName)) return;
      if (visiting.contains(table.sqlName)) return; // Circular dependency

      visiting.add(table.sqlName);

      for (final column in table.columns) {
        if (column.foreignKeyTable != null) {
          final refTable = tables.firstWhere(
            (t) => t.sqlName == column.foreignKeyTable,
            orElse: () => table,
          );
          if (refTable != table) visit(refTable);
        }
      }

      visiting.remove(table.sqlName);
      visited.add(table.sqlName);
      sorted.add(table);
    }

    for (final table in tables) {
      visit(table);
    }

    return sorted;
  }

  String _generateCode(
    List<TableInfo> tables,
    Map<String, String> tableFiles,
    String packageName,
    String? schemaContent,
  ) {
    final buffer = StringBuffer();

    buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
    buffer.writeln('// Generated by native_sqlite_generator');
    buffer.writeln('// coverage:ignore-file');
    buffer.writeln();
    buffer.writeln("import 'dart:convert';");
    buffer.writeln("import 'dart:io';");
    buffer.writeln();

    // Load migrations from schema file at build time
    final migrations = _loadMigrationsFromSchema();
    final deletedTableNames = _loadDeletedTablesFromSchema(schemaContent);
    buffer.writeln("import 'package:flutter/foundation.dart';");
    buffer.writeln("import 'package:native_sqlite/native_sqlite.dart';");
    buffer.writeln();

    for (final table in tables) {
      final relPath =
          tableFiles[table.dartName] ?? 'models/${_toSnakeCase(table.dartName)}';
      buffer.writeln("import 'package:$packageName/$relPath.dart';");
    }

    buffer.writeln();
    buffer.writeln('/// Auto-generated database manager.');
    buffer.writeln('/// Call DatabaseManager.init() at app startup.');
    buffer.writeln('class DatabaseManager {');
    buffer.writeln('  DatabaseManager._();');
    buffer.writeln();
    buffer.writeln('  static bool _initialized = false;');
    buffer.writeln('  static String? _currentDatabaseName;');
    buffer.writeln('  static int? _cachedSchemaVersion;');
    buffer.writeln();

    // Read schema version from JSON file instead of calculating hash
    buffer.writeln('  /// Schema version from native_sqlite_schema.json');
    buffer.writeln(
      '  /// Increments when tables are added, modified, or deleted',
    );
    buffer.writeln('  static int get schemaVersion {');
    buffer.writeln(
      '    if (_cachedSchemaVersion != null) return _cachedSchemaVersion!;',
    );
    buffer.writeln('    try {');
    buffer.writeln(
      "      final file = File('${options.schemaOutputPath}');",
    );
    buffer.writeln('      if (!file.existsSync()) return 0;');
    buffer.writeln('      final content = file.readAsStringSync();');
    buffer.writeln(
      '      final json = jsonDecode(content) as Map<String, dynamic>;',
    );
    buffer.writeln(
      '      _cachedSchemaVersion = json[\'schemaVersion\'] as int? ?? 0;',
    );
    buffer.writeln('      return _cachedSchemaVersion!;');
    buffer.writeln('    } catch (e) {');
    buffer.writeln(
      '      debugPrint(\'⚠️  Failed to read schema version: \$e\');',
    );
    buffer.writeln('      return 0;');
    buffer.writeln('    }');
    buffer.writeln('  }');
    buffer.writeln();

    buffer.writeln('  static const tables = <String, String>{');
    for (final table in tables) {
      buffer.writeln(
        "    '${table.sqlName}': ${table.dartName}Schema.createTableSql,",
      );
    }
    buffer.writeln('  };');
    buffer.writeln();

    buffer.writeln('  static List<String> get onCreateStatements => [');
    for (final table in tables) {
      buffer.writeln('    ${table.dartName}Schema.createTableSql,');
    }
    for (final table in tables) {
      if (table.hasIndexes) {
        buffer.writeln('    ...${table.dartName}Schema.indexSql,');
      }
    }
    buffer.writeln('  ];');
    buffer.writeln();

    buffer.writeln('  static List<String> get tableNames => [');
    for (final table in tables) {
      buffer.writeln("    '${table.sqlName}',");
    }
    buffer.writeln('  ];');
    buffer.writeln();

    // Generate static migration data
    buffer.writeln('  /// Auto-generated migrations from schema changes');
    buffer.writeln('  static const migrations = <Map<String, dynamic>>[');
    for (final migration in migrations) {
      buffer.writeln('    {');
      buffer.writeln("      'tableName': '${migration['tableName']}',");
      buffer.writeln("      'className': '${migration['className']}',");
      buffer.writeln("      'fromVersion': ${migration['fromVersion']},");
      buffer.writeln("      'toVersion': ${migration['toVersion']},");
      buffer.writeln("      'sql': [");
      final sql = migration['sql'] as List;
      for (final statement in sql) {
        final escaped = statement
            .toString()
            .replaceAll(r"'", r"\'")
            .replaceAll(r'$', r'\$');
        buffer.writeln("        '''$escaped''',");
      }
      buffer.writeln('      ],');
      final summary = migration['summary'].toString().replaceAll(r"'", r"\'");
      buffer.writeln("      'summary': '$summary',");
      buffer.writeln('    },');
    }
    buffer.writeln('  ];');
    buffer.writeln();

    buffer.writeln('  /// List of deleted table names');
    buffer.writeln('  static const deletedTableNames = <String>[');
    for (final tableName in deletedTableNames) {
      buffer.writeln("    '$tableName',");
    }
    buffer.writeln('  ];');
    buffer.writeln();

    _generateInitMethod(buffer);
    _generateCloseMethod(buffer);
    _generateGetters(buffer);

    buffer.writeln('}');

    return buffer.toString();
  }

  void _generateInitMethod(StringBuffer buffer) {
    buffer.writeln('  /// Initialize database with automatic setup.');
    buffer.writeln(
      '  /// Handles table creation, migrations, and schema updates automatically.',
    );
    buffer.writeln('  /// ');
    buffer.writeln(
      '  /// - [dropRemovedTables]: If true, tables marked as deleted in',
    );
    buffer.writeln(
      '  ///   native_sqlite_schema.json will be dropped during migration.',
    );
    buffer.writeln('  ///   Default is false for safety.');
    buffer.writeln('  static Future<void> init({');
    buffer.writeln('    String name = \'app_database\',');
    buffer.writeln('    bool enableWAL = true,');
    buffer.writeln('    bool enableForeignKeys = true,');
    buffer.writeln('    bool dropRemovedTables = false,');
    buffer.writeln(
      '    Future<void> Function(String, int, int)? onCustomMigrate,',
    );
    buffer.writeln('  }) async {');
    buffer.writeln('    if (_initialized) {');
    buffer.writeln(
      '      debugPrint(\'DatabaseManager already initialized\');',
    );
    buffer.writeln('      return;');
    buffer.writeln('    }');
    buffer.writeln();
    buffer.writeln('    try {');
    buffer.writeln('      _currentDatabaseName = name;');
    buffer.writeln();
    buffer.writeln('      await NativeSqlite.open(');
    buffer.writeln('        config: AutoMigration.createConfig(');
    buffer.writeln('          name: name,');
    buffer.writeln('          schemaVersion: schemaVersion,');
    buffer.writeln('          onCreateStatements: onCreateStatements,');
    buffer.writeln('          tables: tables,');
    buffer.writeln('          tableNames: tableNames,');
    buffer.writeln('          migrations: migrations,');
    buffer.writeln('          deletedTableNames: deletedTableNames,');
    buffer.writeln('          enableWAL: enableWAL,');
    buffer.writeln('          enableForeignKeys: enableForeignKeys,');
    buffer.writeln('          dropRemovedTables: dropRemovedTables,');
    buffer.writeln('          onCustomMigrate: onCustomMigrate,');
    buffer.writeln('        ),');
    buffer.writeln('      );');
    buffer.writeln();
    buffer.writeln('      _initialized = true;');
    buffer.writeln(
      '      debugPrint(\'✅ DatabaseManager initialized (v\$schemaVersion)\');',
    );
    buffer.writeln('    } catch (e, stack) {');
    buffer.writeln('      debugPrint(\'❌ DatabaseManager init failed: \$e\');');
    buffer.writeln('      debugPrint(stack.toString());');
    buffer.writeln('      rethrow;');
    buffer.writeln('    }');
    buffer.writeln('  }');
    buffer.writeln();
  }

  void _generateCloseMethod(StringBuffer buffer) {
    buffer.writeln('  static Future<void> close() async {');
    buffer.writeln(
      '    if (!_initialized || _currentDatabaseName == null) return;',
    );
    buffer.writeln('    await NativeSqlite.close(_currentDatabaseName!);');
    buffer.writeln('    _initialized = false;');
    buffer.writeln('    _currentDatabaseName = null;');
    buffer.writeln('  }');
    buffer.writeln();
  }

  void _generateGetters(StringBuffer buffer) {
    buffer.writeln('  static bool get isInitialized => _initialized;');
    buffer.writeln();
    buffer.writeln('  static String get currentDatabase {');
    buffer.writeln('    if (!_initialized || _currentDatabaseName == null) {');
    buffer.writeln(
      '      throw StateError(\'Call DatabaseManager.init() first\');',
    );
    buffer.writeln('    }');
    buffer.writeln('    return _currentDatabaseName!;');
    buffer.writeln('  }');
    buffer.writeln();
  }

  int _calculateSchemaHash(List<TableInfo> tables) {
    final content = tables.map((t) => t.sqlName).join(',');
    return content.hashCode.abs() % 1000000;
  }

  String _toSnakeCase(String input) {
    return input
        .replaceAllMapped(
          RegExp(r'([A-Z])'),
          (match) => '_${match.group(1)!.toLowerCase()}',
        )
        .replaceFirst(RegExp(r'^_'), '');
  }

  /// Load migrations from all versioned schema files at build time
  /// This ensures all historical migrations are available at runtime
  List<Map<String, dynamic>> _loadMigrationsFromSchema() {
    try {
      final schemasDir = Directory('lib/generated/schemas');
      if (!schemasDir.existsSync()) {
        log.info('📋 No schemas directory found');
        return [];
      }

      // Find all versioned schema files
      final schemaFiles = schemasDir
          .listSync()
          .whereType<File>()
          .where(
            (f) => f.path.endsWith('.json') && !f.path.endsWith('.gitkeep'),
          )
          .toList();

      if (schemaFiles.isEmpty) {
        log.info('📋 No versioned schema files found');
        return [];
      }

      // Sort by version number
      schemaFiles.sort((a, b) {
        final aMatch = RegExp(r'_v(\d+)\.json').firstMatch(a.path);
        final bMatch = RegExp(r'_v(\d+)\.json').firstMatch(b.path);
        final aVersion = aMatch != null ? int.parse(aMatch.group(1)!) : 0;
        final bVersion = bMatch != null ? int.parse(bMatch.group(1)!) : 0;
        return aVersion.compareTo(bVersion);
      });

      // Collect migrations from all versions
      final allMigrations = <Map<String, dynamic>>[];
      for (final file in schemaFiles) {
        final content = file.readAsStringSync();
        final json = jsonDecode(content) as Map<String, dynamic>;
        final migrations = json['migrations'] as List?;

        if (migrations != null && migrations.isNotEmpty) {
          allMigrations.addAll(migrations.cast<Map<String, dynamic>>());
          log.info(
            '📥 Loaded ${migrations.length} migration(s) from ${file.path.split('/').last}',
          );
        }
      }

      log.info('✅ Total migrations loaded: ${allMigrations.length}');
      return allMigrations;
    } catch (e) {
      log.warning('⚠️  Failed to load migrations: $e');
      return [];
    }
  }

  /// Load deleted table names from schema JSON at build time.
  /// [schemaContent] is read via the build system; if null the schema isn't
  /// ready yet (first build) and we return [] silently.
  List<String> _loadDeletedTablesFromSchema(String? schemaContent) {
    if (schemaContent == null) return [];
    try {
      final json = jsonDecode(schemaContent) as Map<String, dynamic>;
      final deleted = json['deletedTables'] as List? ?? [];
      return deleted
          .cast<Map<String, dynamic>>()
          .map((t) => t['tableName'] as String)
          .toList();
    } catch (e) {
      return [];
    }
  }
}
