import 'package:native_sqlite_platform_interface/native_sqlite_platform_interface.dart';

/// Utility class for automatic database schema migration.
///
/// This class provides helpers for auto-generated schema registries
/// to handle database migrations automatically.
class AutoMigration {
  AutoMigration._();

  /// Create a DatabaseConfig with automatic migration support.
  ///
  /// Used by the `DatabaseManager` generated by native_sqlite_generator:
  ///
  /// * a new database runs [onCreateStatements];
  /// * an existing database at version `old` runs [migrations] steps
  ///   `old + 1 .. schemaVersion` in order, then [ensureSchemaStatements]
  ///   (idempotent `CREATE ... IF NOT EXISTS` repairs), atomically.
  ///
  /// The platform (Android, iOS or web) applies the steps while opening, so
  /// the result is identical whether Dart or native code opens it first.
  static DatabaseConfig createConfig({
    required String name,
    required int schemaVersion,
    required List<String> onCreateStatements,
    Map<int, List<String>> migrations = const {},
    List<String> ensureSchemaStatements = const [],
    bool enableWAL = true,
    bool enableForeignKeys = true,
  }) {
    return DatabaseConfig(
      name: name,
      version: schemaVersion,
      onCreate: onCreateStatements,
      migrations: migrations,
      onUpgrade: ensureSchemaStatements,
      enableWAL: enableWAL,
      enableForeignKeys: enableForeignKeys,
    );
  }
}
