import 'package:native_sqlite_platform_interface/native_sqlite_platform_interface.dart';

/// Utility class for automatic database schema migration.
///
/// This class provides helpers for auto-generated schema registries
/// to handle database migrations automatically.
class AutoMigration {
  AutoMigration._();

  /// Create a DatabaseConfig with automatic migration support.
  ///
  /// This method integrates with schema registries generated by
  /// native_sqlite_generator to automatically handle table creation
  /// and migration when the schema version changes.
  ///
  /// Example:
  /// ```dart
  /// await NativeSqlite.open(
  ///   config: AutoMigration.createConfig(
  ///     name: 'my_database',
  ///     schemaVersion: DatabaseSchemaRegistry.schemaVersion,
  ///     onCreateStatements: DatabaseSchemaRegistry.onCreateStatements,
  ///     tables: DatabaseSchemaRegistry.tables,
  ///     tableNames: DatabaseSchemaRegistry.tableNames,
  ///   ),
  /// );
  /// ```
  static DatabaseConfig createConfig({
    required String name,
    required int schemaVersion,
    required List<String> onCreateStatements,
    required Map<String, String> tables,
    required List<String> tableNames,
    List<String> deletedTableNames = const [],
    bool enableWAL = true,
    bool enableForeignKeys = true,
    bool dropRemovedTables = false,
    Future<void> Function(String databaseName, int oldVersion, int newVersion)?
    onCustomMigrate,
  }) {
    return DatabaseConfig(
      name: name,
      version: schemaVersion,
      onCreate: onCreateStatements,
      onMigrateCallback: (oldVersion, newVersion) async {
        return await _generateMigrationSQL(
          name: name,
          tables: tables,
          tableNames: tableNames,
          deletedTableNames: deletedTableNames,
          dropRemovedTables: dropRemovedTables,
          onCustomMigrate: onCustomMigrate,
          oldVersion: oldVersion,
          newVersion: newVersion,
        );
      },
      enableWAL: enableWAL,
      enableForeignKeys: enableForeignKeys,
    );
  }

  /// Generate SQL statements for automatic migration.
  static Future<List<String>> _generateMigrationSQL({
    required String name,
    required Map<String, String> tables,
    required List<String> tableNames,
    required List<String> deletedTableNames,
    required bool dropRemovedTables,
    required Future<void> Function(String, int, int)? onCustomMigrate,
    required int oldVersion,
    required int newVersion,
  }) async {
    final statements = <String>[];

    // Drop deleted tables if flag is enabled
    if (dropRemovedTables && deletedTableNames.isNotEmpty) {
      for (final tableName in deletedTableNames) {
        statements.add('DROP TABLE IF EXISTS $tableName');
      }
    }

    // Add new tables - CREATE TABLE IF NOT EXISTS is safe
    for (final tableName in tableNames) {
      statements.add('CREATE TABLE IF NOT EXISTS ${tables[tableName]}');
    }

    // Call custom migration callback
    if (onCustomMigrate != null) {
      await onCustomMigrate(name, oldVersion, newVersion);
    }

    return statements;
  }

  /// Helper to detect new tables that need to be created.
  ///
  /// This should be called after database is opened to check for
  /// tables that don't exist yet.
  static Future<List<String>> detectNewTables({
    required String databaseName,
    required Map<String, String> tables,
    required List<String> tableNames,
    required Future<List<Map<String, dynamic>>> Function(String sql) queryFn,
  }) async {
    final result = await queryFn(
      "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'",
    );

    final existingTables = result.map((row) => row['name'] as String).toSet();
    final newStatements = <String>[];

    for (final tableName in tableNames) {
      if (!existingTables.contains(tableName)) {
        newStatements.add(tables[tableName]!);
      }
    }

    return newStatements;
  }

  /// Helper to detect removed tables that should be dropped.
  static Future<List<String>> detectRemovedTables({
    required List<String> tableNames,
    required Future<List<Map<String, dynamic>>> Function(String sql) queryFn,
  }) async {
    final result = await queryFn(
      "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'",
    );

    final existingTables = result.map((row) => row['name'] as String).toSet();
    final dropStatements = <String>[];

    for (final tableName in existingTables) {
      if (!tableNames.contains(tableName)) {
        dropStatements.add('DROP TABLE IF EXISTS $tableName');
      }
    }

    return dropStatements;
  }
}
