name: native_sqlite_annotations
description: Annotations for native_sqlite generator.
version: 0.0.1
homepage: https://nesmin.dev
resolution: workspace

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  meta: ^1.16.0

dev_dependencies:
  lints: ^6.0.0
